### PR TITLE
Migrate from libcce after archiving that

### PR DESCRIPTION
**Pull request by katrinleinweber**
There are still some more commits, maybe, but cherry-picking revealed some conflicts. I need to sort this out on the Mac.

### CODE REVIEW

**Comment by katrinleinweber** [comment]
Hi @libcce! This is getting more important, because in workshops, people can't search this repo to find places to improve, because GitHub disallows searching forks like this repo still is.

**Comment by libcce** [comment]
Thanks @katrinleinweber 😄 I've archived libcce/Top-10-FAIR. All the commits above are reflected in the current LibraryCarpentry/Top-10-FAIR. Let's see if archiving the repo helps.

**Comment by katrinleinweber** [comment]
It doesn't seem so: It still says `forked from libcce/Top-10-FAIR` at the very top and [code search still returns `Sorry, forked repositories are not currently searchable.`](https://github.com/LibraryCarpentry/Top-10-FAIR/search?q=zenodo&type=Code). Please try deleting your repo.

**Comment by libcce** [comment]
Deleted. Didn't seem to work 😞 It reverted back to the gfjaru/Kiko fork (which is now archived). Re-importing the repo might work here?

**Comment by katrinleinweber** [comment]
Damn :-( It's either

a) [contacting GH support](https://stackoverflow.com/a/16052845/4341322) then, or 
b) [recreating this repo under a new name, deleting this copy, and renaming the new copy](https://github.community/t5/How-to-use-Git-and-GitHub/De-forking-a-Github-repo/td-p/2785)

**Comment by libcce** [comment]
I went for option a to start. Fingers crossed. 🤞

**Comment by libcce** [comment]
Huzzah! @katrinleinweber GitHub Developer Support unforked this repo so you can search it now 😄

**Pull request closed without merging**
