### PR TITLE
About section

### PR DESCRIPTION
**Pull request by evertrol**
This adds a short descriptive paragraph to both the description (HTML meta description tag in the rendered output) and the README file.

This is a follow-up from #20 . I've simply copy-pasted the text from the front page (which was effectively introduced in #20 ), since that seems perfect for this already, and makes it more consistent overall.

### CODE REVIEW

**Comment by libcce** [comment]
Thanks!!!

**Comment by doujouDC** [comment]
Hi everyone...sorry I am late to the game. I have been swamped with
projects and travel. Should we all try to get together to discuss our
strategy for maintaining these lessons. Liz, Juande and I have been
chatting via email.

Doug

**Comment by libcce** [comment]
Hi @evertrol there was a build error when I merged this due to the use of double quotes in the description. I've changed it to single quotes and all is well. Thanks again!

@doujouDC best thing is to move to using the teams functionality. It works much like a listserv where the message goes to everyone (who may have missed the email thread with you, Liz, and Juande. I'll set that up.

**Comment by evertrol** [comment]
Ah, apologies. I should have build it properly locally first, that would have shown this. Sounds like the problem was obvious enough that it good be quickly fixed; thanks for that.

**Comment by doujouDC** [comment]
Hey Everyone,

I finally have some free time so I can start reading all of the emails
related to managing these lessons. So, a basic question.  Do I use GitHub
desktop (my preferred tool), to connect to this repository? Is this how
changes are made and managed?

Thanks

Doug

**Comment by libcce** [comment]
It’s a matter of preference but I know a number of people who use Desktop. We have to review issues and pull requests as they are made. Generally it’s good to get consensus from two Maintainers but sometimes it’s fine to merge if the change is minor like a spelling mistake or when a pull request has been waiting to be merged forever.  BTW, again, I created a teams page so that we can send messages to everyone like this. The teams site is linked to from the readme page.

**Comment by doujouDC** [comment]
Hi Chris,

Thanks so much for setting up the teams page. I will definitely check out
the README file. So, and I apologize for asking a lot of questions I’ve
never done this before..how are tasks/change requests assigned?

Doug

**Comment by doujouDC** [comment]
Thanks, Chris. So I would simply clone this repository in GitHub desktop
using the following URL:  https://github.com/LibraryCarpentry/Top-10-FAIR ?

Thanks

Doug

**Comment by libcce** [comment]
Hi @doujouDC that's the repo link, yes. And we use issues/pull requests to assign tasks 😄 Thanks!

**Pull request merged**
